version: "2.2"

services:

  server:
    platform: linux/amd64 
    build:
      context: .
      target: server
    command: "npm run start"
    ports:
      - "8080:8080"
    networks:
      - sqlinject

  client:
    platform: linux/amd64 
    build:
      context: .
      target: client
    command: "npm run dev"
    ports:
      - "8081:8081"
    networks:
      - sqlinject
    depends_on:
      - server

networks:
  sqlinject:
